version: "3.8"

services:
  db:
    image: postgres
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pokazna
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  local_pgdata:
